feat: Compatible with vcpkg package manager
Decodetalkers/neocmakelsp pull request #95
Opened 2024-08-09 11:10 UTC by denstiny

vcpkg is the most commonly used package management tool for C++ users. Since neocmakelsp only searches the system's cmake package, it cannot adapt to the vcpkg package manager. This is regrettable, so I created this pr
It helps users search for packages installed by vcpkg

2024-08-09 11:23 UTC, Decodetalkers commented on src/complete.rs
> +use crate::CompletionResponse;
this was a mistake , it should imported from tower_lsp::lsp_types, lol

2024-08-09 11:26 UTC, Decodetalkers commented on src/utils/findpackage/vcpkg.rs
> +    let lib_paths: Vec<&'static str> = [
emm. I do not think 'static is needed

2024-08-09 11:26 UTC, Decodetalkers commented on src/utils/findpackage/vcpkg.rs
> +    .to_vec();
this is also not needed I think

2024-08-09 11:27 UTC, Decodetalkers commented on src/utils/findpackage/vcpkg.rs
> +pub fn make_vcpkg_package_search_path(search_path: &Path) -> std::io::Result<Vec<String>> {
there is no error here, I think there is no need to return Result

2024-08-09 11:29 UTC, Decodetalkers commented
there is some clippy worning. Emm you can run the clippy check

2024-08-09 11:44 UTC, Decodetalkers requested changes

2024-08-09 11:44 UTC, Decodetalkers commented on src/utils/findpackage/vcpkg.rs
> +    for prefix in VCPKG_PREFIX.lock().unwrap().iter() {
This is bad.. you should

```rust
let vcpkg_prefix = VCPKG_PREFIX.lock().unwrap();
let vcpkg_libs = VCPKG_LIBS.lock().unwrap()
```

then use the locked variable

2024-08-09 11:54 UTC, Decodetalkers commented
Thanks for your effort!

2024-08-09 11:54 UTC, merged

2024-08-18 08:45 UTC, meinzer1899 commented
I did not understand what this PR adds. 
Can you help me?

2024-08-18 08:52 UTC, Decodetalkers commented
> I did not understand what this PR adds. Can you help me?

when use you are using vcpkg, it will try to find packages under vcpkg folder, if you are not using vcpkg, it will behave like before. Just find package from additional place